serviceName: "chat"
environment: "dev"
httpServer:
  host: "0.0.0.0"
  port: "8080"
scylladb:
  hosts:
    - "127.0.0.1"
  port: "9042"
  keyspace: "chat" 
  username: "chat-user"
  password: "chat-password"
  replicationFactor: 3
  consistency: 1
nats:
  host: "nats"
  port: 4222
