serviceName: "chat"
appEnvironment: "dev"
httpServer:
  host: "0.0.0.0"
  port: "8080"
scylladb:
  hosts:
    - "127.0.0.1"
  port: "9042"
  keyspace: "chat-keyspace"
  username: "chat-user"
  password: "chat-password"
